markdown : rdiscount
permalink : /:year/:month/:day/:title.html
rdiscount extensions : [smart]
title: Mike Rogers
description: The occasional ramblings on programming and technology.
rss_path: /rss.xml
cdn_uri: http://mikerogers.io

name: Mike Rogers
pygments: true

production_url : http://mikerogers.io

sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed